// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfajfuvpmixxhcyofmzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mYWpmdXZwbWl4eGhjeW9mbXp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMDg1NjIsImV4cCI6MjA2NjU4NDU2Mn0.XRh0yfU3BTGfVtYuFSoFKQocPahbBhq48a0j2u0VmxE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);